name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cmake -G "Unix Makefiles" ./ && make
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: Lab
